### PR TITLE
Support rails 5.1

### PR DESCRIPTION
**Pull request by mcls**
This builds upon my previous changes form https://github.com/iangreenleaf/native_enum/pull/12 to support rails 5.1

Related issue: https://github.com/iangreenleaf/native_enum/issues/11

Note: I also decided to switch to using [`appraisal`](https://github.com/thoughtbot/appraisal) to make it a bit easier to test the different ruby version and Gemfile combinations. The Travis config was also updated to excluded unsupported ruby version and Gemfile combos.

### CODE REVIEW

**Comment by gerryster** [comment]
@iangreenleaf : what are your thoughts on this? My opinion is that it is a high quality pull request with some nice infrastructure additions to the test suite. I would love to see this merged into master and a new version of the gem to be released. Until then, I will have to work around this fix not being applied by forking https://github.com/fruwe/native_enum .

**Comment by iangreenleaf** [comment]
@gerryster thanks for the review and the nudge! You're right, I should get this merged and  I feel bad that I haven't done so yet. It's been on my to-do list for months now and just keeps slipping down. I'll aim to get to it this week.

**Comment by gerryster** [comment]
Thanks a lot @iangreenleaf! Let me know if there is anything I can do to help.

**Comment by gerryster** [comment]
One thing to mention is that I've been using this branch successfully on Rails 5.2.

**Comment by iangreenleaf** [comment]
Done! Thank you @mcls and @fruwe for the good code and @gerryster for the review and gentle nudge. This is now released as v2.0.0.

**Comment by mcls** [comment]
Thanks!

**Comment by gerryster** [comment]
Thanks again @iangreenleaf !

**Pull request merged**
