### PR TITLE
Add Rails 7 support

### PR DESCRIPTION
**Pull request by denisahearn**
We have been using a fork of the gem with these same Rails 7 compatibility changes for several weeks now and it seems to be working well for us.

### CODE REVIEW

**Comment by iangreenleaf** [comment]
Thanks for the contribution! Is this writing the `schema.rb` correctly for you? I'm seeing test failures from that. For example:

```
  1) ENUM datatype schema dump dumps native format
     Failure/Error: expect(subject).to match %r{t\.enum\s+"color",\s+(:limit =>|limit:) \["blue", "red", "yellow"\]}
     
       expected "\nActiveRecord::Schema[7.0].define(version: 2015_11_01_223435) do\n  create_table \"aircraft\", char... \"green,gold\", null: false\n    t.column \"gasses\", \"set('helium','hydrogen')\"\n  end\n\nend\n" to match /t\.enum\s+"color",\s+(:limit =>|limit:) \["blue", "red", "yellow"\]/
       Diff:
       @@ -1,12 +1,23 @@
       -/t\.enum\s+"color",\s+(:limit =>|limit:) \["blue", "red", "yellow"\]/
       +
       +ActiveRecord::Schema[7.0].define(version: 2015_11_01_223435) do
       +  create_table "aircraft", charset: "utf8mb3", force: :cascade do |t|
       +    t.column "color", "enum('blue','red','yellow')", default: "red", null: false
       +  end
       +
       +  create_table "balloons", charset: "utf8mb3", force: :cascade do |t|
       +    t.column "ribbons", "set('red','green','gold')", default: "green,gold", null: false
       +    t.column "gasses", "set('helium','hydrogen')"
       +  end
       +
       +end
       
     # ./spec/enum_spec.rb:10:in `block (3 levels) in <top (required)>'

```

**Comment by iangreenleaf** [comment]
@denisahearn the way this gem is supposed to output that schema is something like:

```
t.enum "license_status", default: "active", null: false, limit: %w[active suspended canceled]
```

Is it really necessary for it to do that? I don't know, but it would be nice to maintain behavior between versions. It's been quite a few years since I've used this gem myself, so I haven't been thinking super hard about it.

**Comment by denisahearn** [comment]
@iangreenleaf Sorry for the delayed response. I created a new Rails app using Rails 6.1.7, and added version 2.0.0 of `native_enum` to this app, and then ran this database migration:

```
class CreateBallons < ActiveRecord::Migration[6.1]
  def change
    create_table :ballons do |t|
      t.enum "color", :limit => ['red', 'gold'], :default => 'gold', :null => false
      t.timestamps
    end
  end
end
```

The resulting schema.rb has this:

```
ActiveRecord::Schema.define(version: 2022_11_23_165430) do

  create_table "ballons", charset: "utf8", force: :cascade do |t|
    t.column "color", "enum('red','gold')", limit: ["red", "gold"], default: "gold", null: false
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

end
```

It looks like the gem, prior to my changes, is outputting a different format to schema.rb than you are expecting. Are you perhaps conflating the syntax you can use in the database migration (i.e. `.enum "color", :limit => ['red', 'gold'], :default => 'gold', :null => false`) with the syntax that gets outputted to schema.rb (e.g. `t.column "color", "enum('red','gold')", limit: ["red", "gold"], default: "gold", null: false`)?

My test Rails app is attached below in case you want to take a look.

[native_enum_test.zip](https://github.com/iangreenleaf/native_enum/files/10077713/native_enum_test.zip)

**Comment by iangreenleaf** [comment]
@denisahearn the intent of this gem is to hook into both the dump and load actions so that it can use the standardized format everywhere. It doesn't support Rails 6, though, so it's not surprising that it's not working there.

With Rails 5 on mysql, for example, this is the resulting schema:

```ruby
ActiveRecord::Schema.define(version: 20221210210316) do

  create_table "ballons", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci" do |t|
    t.enum "color", limit: ["red", "gold"], default: "gold", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

end
```

If you're happy with the other format, then my guess would be that you don't really need this gem for anything. I assume you could write your migrations with the same `t.column "color", "enum('red','gold')"` format and be good to go.

TBH I'm thinking I should deprecate this gem. It's very far behind, and I think most folks are either off MySQL or have found other solutions. I personally haven't used this gem in production in almost a decade.

**Comment by iangreenleaf** [comment]
Sunsetting this gem, for the reasons described above.

**Pull request closed without merging**
